// Note that this file only runs serverside

const React     = require('react');
const PostStore = require('./stores/PostStore');

const Skeleton = React.createClass({
  render () {
    let user = this.props.user;
    const innerHTML = this.props.innerHTML;

    const serverLocation = process.env.ENVIRONMENT === 'production'
      ? ''
      : 'http://localhost:8899/dist';

    const webpackDevServer = process.env.ENVIRONMENT === 'development'
      ? <script src="http://localhost:8899/webpack-dev-server.js" type="text/javascript" />
      : '';

    /* Get the state of the app */
    let state = {
      posts: PostStore.getPosts().toArray()
    };

    /* Build initial react state variable to be consumed on browser init */
    var reactState = 'var initialReactState=' + JSON.stringify(state) + ';';

    return (
      <html>
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="robots" content="NOODP" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />

          <title>{this.props.title}</title>

          <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

          {webpackDevServer}

          {/* Main style sheet generated by site.scss */}
          <link href={serverLocation + '/site.css'} rel="stylesheet" />


        </head>
        <body>
          <section id="app" dangerouslySetInnerHTML={{__html: innerHTML}} />
          <script dangerouslySetInnerHTML={{__html: reactState}} />

          <script src={serverLocation + '/site.js'} type="text/javascript" />

        </body>
      </html>
    );
  }
});

module.exports = Skeleton;